# Generated by Django 3.1.4 on 2021-03-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='date_of_birth',
            field=models.CharField(max_length=100),
        ),
    ]
